//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace Hugo_Rule_Exercise_Service
{
    
    [DataContract(Name = "shapeDto", Namespace = "" , IsReference = true) ]
    public partial class shapeDto
    {
         #region Primitive Properties
    	
    	[DataMember]
        public virtual int id_shape
        {
            get;
            set;
        }
    	
    	[DataMember]
        public virtual string name
        {
            get;
            set;
        }
    	
    	[DataMember]
        public virtual string coordinates
        {
            get;
            set;
        }
    	
    	[DataMember]
        public virtual double area
        {
            get;
            set;
        }
    	
    	[DataMember]
        public virtual System.DateTime date_created
        {
            get;
            set;
        }
    	
    	[DataMember]
        public virtual byte is_valid
        {
            get;
            set;
        }

        #endregion
    }
}
